### PR TITLE
added 'xlhost.de' as provider

### PR DESCRIPTION
**Pull request by micbuh**
please merge to master branch. so, hopefully no patching after ipfire core upgrade.

### CODE REVIEW

**Comment by DaStevee** [comment]
Hello micbuh,

please provide your real name and a valid mail address, otherwise we are not going to merge your changes.

Thanks in advance,
-Stefan

**Comment by micbuh** [comment]
Hi Stefan,

I updated my profile. You may take the requested information from there.

BR, Michael

**Comment by DaStevee** [comment]
Hello Michael,

a big thanks for providing the missing user details.

I've another question to your changes:

In your code you are using the keyword "address" in combination with the following public IP address, which will sent to the update server. In the providers documentation I read about they are using the DynDNS 2 Protocol for update requests which requires "myip", also in the example pictures there has been used "myip" as keyword.

Which one of these two keywords can be used? Do you already have tested your code and verified it is working well?

Thanks in advance,

-Stefan

**Comment by micbuh** [comment]
Hello Stefan,

I just verified that "myip" works as well. As this seems to be according to spec, I committed this change.

Hope it's ok now.

Michael

**Comment by mtremer** [comment]
That looks good. However the prepare_request_data is overwritten with an almost identical function. So you can remove that as well.

https://github.com/micbuh/ddns/blob/master/src/ddns/providers.py#L354

So this would look like this: https://github.com/micbuh/ddns/blob/master/src/ddns/providers.py#L872

**Comment by DaStevee** [comment]
I've already done the required final changes and merged them into the ddns master.

Thanks for contributing.

**Pull request closed without merging**
